sonar.projectKey=taskflow_frontend_key
sonar.organization=mficius
sonar.host.url=${SONAR_HOST_URL}
sonar.sources=src
sonar.branch.name=master

# Exclusions propres
sonar.exclusions=**/node_modules/**,**/build/**,**/dist/**

sonar.sourceEncoding=UTF-8
 
# Coverage (important pour qualité)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info 