name: Mon pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test-frontend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Executer Node js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Version LTS stable recommandée

      - name: Installer les dependances
        run: npm ci

      # - name: Executer les tests
      #   run: npm test -- --coverage --watchAll=false

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


  build:
    runs-on: ubuntu-24.04
    needs: test-frontend # Optionnel: empêche le build si les tests échouent
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Corrigé pour utiliser votre secret
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire l'image frontend
        run: |
          docker build \
            -t ${{ env.DOCKER_USERNAME }}/taskflow:${{ env.IMAGE_TAG }} .

      - name: Scanner l'image avec Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: ${{ env.DOCKER_USERNAME }}/taskflow:${{ env.IMAGE_TAG }}
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Pusher l'image 
        run: |
          docker push ${{ env.DOCKER_USERNAME }}/taskflow:${{ env.IMAGE_TAG }}

